
@startuml
'https://plantuml.com/sequence-diagram
skinparam defaultFontName 微软雅黑
开始界面 -> 选择难度: 单机模式
开始界面 -> 等待对手加入: 联机模式
等待对手加入 -> 游戏界面: 匹配成功
选择难度 -> 游戏界面: 简单难度
选择难度 -> 游戏界面: 普通难度
选择难度 -> 游戏界面: 困难难度
游戏界面 -> 排行榜: 游戏结束
排行榜 -> 开始界面: 再来一局
@enduml